version: '3'
services:
  grpc_server:
    image: localhost/grpc-todo-app
    ports:
      - "9192:9192"

  envoy:
    image: envoyproxy/envoy:v1.21.0
    ports:
      - "8081:8081"
      - "9901:9901"
    volumes:
      - ./docker/envoy.yaml:/etc/envoy/envoy.yaml
