name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "29.3"

    - name: maven version
      run: mvn -version

    - name: Download maven dependencies
      run: mvn dependency:resolve-plugins dependency:go-offline --file grpc-todo/pom.xml

    - name: Build with Maven
      run: mvn clean package --file grpc-todo/pom.xml

    - name: Print protoc version
      run: protoc --version

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
    - run: cd client && npm ci && npm run build
